const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const source = path.join(__dirname, '../assets/image-tools-core.js');
assert.ok(fs.existsSync(source), 'image tools geometry is missing');
const core = require(source);
assert.equal(typeof core.editStatus,'function','separate image save status is missing');
assert.equal(core.editStatus({ready:true,revision:0}),'empty','an unannotated image is not a saved document');
assert.equal(core.editStatus({ready:true,revision:1}),'saved');
assert.equal(core.editStatus({ready:true,revision:1,dirty:true}),'dirty');
assert.equal(core.editStatus({ready:true,dirty:true,pendingText:true}),'pending');
assert.equal(core.editStatus({ready:true,dirty:true,saving:true}),'saving');
assert.equal(core.editStatus({ready:true,dirty:true,error:true}),'error');
assert.equal(core.editStatus({ready:true,readonly:true}),'snapshot');
assert.equal(core.editStatus({ready:false}),'loading');
assert.equal(typeof core.isSaveShortcut,'function','save shortcut cannot distinguish text-edit context');
assert.equal(core.isSaveShortcut({key:'s',metaKey:true,editing:true}),true);
assert.equal(core.isSaveShortcut({key:'S',ctrlKey:true}),true);
assert.equal(core.isSaveShortcut({key:'s'}),false);
assert.equal(core.isSaveShortcut({key:'s',ctrlKey:true,altKey:true}),false);
assert.equal(typeof core.pointInImage,'function','image drawing bounds check is missing');
assert.equal(core.pointInImage({x:0,y:0},120,60),true);
assert.equal(core.pointInImage({x:120,y:60},120,60),true);
assert.equal(core.pointInImage({x:-.01,y:30},120,60),false);
assert.equal(core.pointInImage({x:40,y:61},120,60),false);
assert.equal(core.pointInImage({x:NaN,y:30},120,60),false);
assert.equal(typeof core.toolShortcut,'function','image observation tool shortcuts are missing');
assert.equal(core.toolShortcut({key:'v'}),'pan');
assert.equal(core.toolShortcut({key:'z'}),'zoom');
assert.equal(core.toolShortcut({key:'r'}),'ruler');
assert.equal(core.toolShortcut({key:'t'}),'text');
assert.equal(core.toolShortcut({key:'z',ctrlKey:true}),null,'system undo remains separate from the zoom tool');
assert.equal(core.toolShortcut({key:'t',editing:true}),null,'typing must not change tools');
assert.equal(core.toolShortcut({key:'r',isComposing:true}),null,'IME composition must not change tools');
assert.equal(typeof core.viewSnapshot,'function','relative comparison view snapshot is missing');
const snapshot=core.viewSnapshot({x:-200,y:-100,scale:2},1000,600,800,600);
assert.ok(Math.abs(snapshot.u-.3)<1e-12);assert.ok(Math.abs(snapshot.v-1/3)<1e-12);
const linked=core.fromViewSnapshot(snapshot,2000,1200,800,600);
assert.ok(Math.abs(linked.scale-1)<1e-12);
const linkedCenter=core.toImage({x:400,y:300},linked);
assert.ok(Math.abs(linkedCenter.x/2000-snapshot.u)<1e-12);
assert.ok(Math.abs(linkedCenter.y/1200-snapshot.v)<1e-12);
assert.equal(core.viewSnapshot({x:0,y:0,scale:1},0,0,800,600),null);
const view = {x:30,y:20,scale:2};
assert.deepEqual(core.toImage({x:230,y:120},view), {x:100,y:50});
const zoom = core.zoomAt(view,{x:230,y:120},4);
assert.deepEqual(core.toImage({x:230,y:120},zoom), {x:100,y:50},'zoom must preserve point under pointer');
assert.deepEqual(core.box({x:90,y:80},{x:10,y:20}),{x:10,y:20,width:80,height:60});
assert.deepEqual(core.measure({x:0,y:0},{x:3,y:4}),{dx:3,dy:4,distance:5});
assert.deepEqual(core.clampPoint({x:-10,y:200},120,60),{x:0,y:60});
const fitted = core.fitBox({x:100,y:50,width:200,height:100},800,600,0);
assert.equal(fitted.scale,4);
assert.deepEqual(core.toImage({x:0,y:100},fitted),{x:100,y:50});
assert.equal(core.fitBox({x:10,y:20,width:0,height:0},800,600),null,'zero-area zoom must not change view');
const ticks=core.ticks(100,1200,2,30);
assert.ok(ticks.length<50);
assert.ok(ticks.every((t,i)=>i===0||t.value>ticks[i-1].value));
assert.equal(ticks[0].screen,30+ticks[0].value*2);
const moved=core.moveShape({type:'rect',points:[{x:10,y:10},{x:30,y:20}]},-100,100,120,60);
assert.deepEqual(moved.points,[{x:0,y:50},{x:20,y:60}],'move must preserve dimensions at bounds');
const history=new core.History([]);
assert.equal(typeof history.clear,'function','one-click clear markup history is missing');
const existing=[{id:'saved',type:'line',points:[{x:1,y:2},{x:3,y:4}]}];
const cleared=new core.History(existing);
assert.deepEqual(cleared.clear(),[]);
assert.deepEqual(cleared.undo(),existing,'clear must restore all pre-existing saved marks with undo');
assert.deepEqual(cleared.redo(),[]);
assert.deepEqual(core.observationTools,['pan','zoom','ruler'],'inspection tools remain available while annotation tools are collapsed');
history.push([{type:'line',points:[{x:0,y:0},{x:3,y:4}]}]);
assert.equal(history.undo().length,0);
assert.equal(history.redo().length,1);
history.undo();history.push([{type:'text',text:'new'}]);
assert.equal(history.canRedo,false);
console.log('image tools: original-pixel coordinates, centered zoom, box fit, rulers, bounded moves and history PASS');
