const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const source = path.join(__dirname, '../assets/workspace-core.js');
assert.ok(fs.existsSync(source), 'workspace behavior module is missing');
const core = require(source);
assert.equal(typeof core.isSettingsShortcut, 'function', 'settings shortcut handler missing');
assert.equal(core.isSettingsShortcut({key:',',metaKey:true}),true);
assert.equal(core.isSettingsShortcut({key:',',ctrlKey:true}),true);
assert.equal(core.isSettingsShortcut({key:',',metaKey:true,shiftKey:true}),false);
assert.equal(core.isSettingsShortcut({key:',',metaKey:false}),false);
assert.equal(typeof core.sameImportOptions,'function','settings form comparison missing');
assert.equal(core.sameImportOptions({}, {folder_id:null,tags:[],hierarchy:false,auto_export:true}),true);
assert.equal(core.sameImportOptions({tags:[]},{tags:['pending']}),false);
assert.equal(core.sameImportOptions({auto_export:false},{}),false);
const tree = [{id:'a',parent_id:null},{id:'b',parent_id:'a'},{id:'c',parent_id:'b'}];
assert.deepEqual([...core.descendants(tree,'a')], ['a','b','c']);
assert.deepEqual([...core.rangeSelection(new Set(['outside']),['a','b','c','d'],'a','d',true)], ['outside','a','b','c','d']);
assert.deepEqual([...core.rangeSelection(new Set(),['a','b','c'],'c','a',true)], ['a','b','c']);
const r={title:'Stress curve',filename:'plot.svg',asset_kind:'image',tags:['LC'],fields:{rate:'slow'},favorite:1};
assert.equal(core.matches(r,{search:'stress curve',tags:['LC'],favorite:true,fields:{rate:'slow'}}),true);
assert.equal(core.matches(r,{tags:['missing']}),false);
assert.equal(core.matches(r,{kind:'document'}),false);
assert.equal(core.isImage({filename:'data.csv'}),false);
assert.equal(core.isImage({filename:'plot.SVG'}),true);
console.log('workspace core: hierarchy, unlimited/range selection, smart predicates, generic assets PASS');
