const assert=require('node:assert/strict');
const core=require('../assets/workspace-core.js');
assert.equal(typeof core.activeFilters,'function','active browse filters are missing');
const view={mode:'library',library:'library-a',folder:'',search:' curve ',kind:'image',group:'group-a',filters:{rate:'slow',empty:''},page:3};
const tokens=core.activeFilters(view);
assert.deepEqual(tokens.map(t=>[t.kind,t.key,t.value]),[['search','search','curve'],['kind','kind','image'],['group','group','group-a'],['field','rate','slow']]);
const removed=core.removeFilter(view,tokens[3]);
assert.equal(removed.filters.rate,undefined);
assert.equal(removed.library,'library-a');
assert.equal(removed.page,1);
assert.equal(view.filters.rate,'slow','removing a filter must not mutate prior state');
const widened=core.widenSearch(view);
assert.equal(widened.mode,'all');assert.equal(widened.library,'');assert.equal(widened.folder,'');
assert.equal(widened.search,' curve ','expanding scope must retain the typed query');
assert.equal(widened.kind,'image');assert.deepEqual(widened.filters,{});assert.equal(widened.group,'');
console.log('UX: filter visibility, reversible removal and broader search preserve the user query PASS');
assert.equal(typeof core.selectionSummary,'function','selection visibility summary is missing');
assert.deepEqual(core.selectionSummary(new Set(['a','b','c']),['b','c','d']),{total:3,visible:2,outside:1});
assert.equal(typeof core.gridNeighbor,'function','keyboard grid navigation is missing');
assert.equal(core.gridNeighbor(['a','b','c','d','e'],'b','ArrowDown',2),'d');
assert.equal(core.gridNeighbor(['a','b','c'],'b','ArrowUp',2),'b','top-row upward navigation stays in its column');
assert.equal(core.gridNeighbor(['a','b','c'],'c','ArrowRight',2),'c','navigation must stay within the visible page');
assert.equal(core.gridNeighbor(['a','b','c'],'b','Home',2),'a');
assert.equal(core.gridNeighbor(['a','b','c'],'b','End',2),'c');
assert.equal(typeof core.folderMembershipState,'function','partial folder membership state is missing');
assert.deepEqual(core.folderMembershipState(1,3),{checked:false,indeterminate:true});
assert.deepEqual(core.folderMembershipState(3,3),{checked:true,indeterminate:false});
assert.deepEqual(core.folderMembershipState(0,0),{checked:false,indeterminate:false});
assert.equal(typeof core.comparisonColumns,'function','image-aware comparison layout is missing');
assert.equal(core.comparisonColumns(4,1200,520,[5/3,5/3,5/3,5/3]),4);
assert.equal(core.comparisonColumns(4,1200,520,[3,3,3,3]),2,'wide images need taller two-row cells');
assert.equal(core.comparisonColumns(3,1200,520,[5/3,5/3,5/3]),3);
assert.equal(core.comparisonColumns(4,390,640,[5/3,5/3,5/3,5/3]),1,'narrow view scrolls readable cells');
